### ISSUE TITLE
Google provider required?

### ISSUE THREAD

**Issue by kayibal** [cloudhut/terraform-modules#5]
Hi why do you require the google provider in version? I would like to test this on an existing EKS cluster. I would like to avoid the google provider. 

It seems to be unnecessary or is this chart restricted to be used with google kubernetes clusters?

**Comment by weeco** [comment]
@kayibal Good issue, the Google provider obviously should not be required! I think that's a leftover from older versions. I assume removing it from the required block should already fix it.

**Comment by weeco** [comment]
@kayibal Update the terraform module and try again now :)

**Comment by kayibal** [comment]
Thx I also needed to update the random provider, opened a PR in case you are interested in merging that :)
